name = "PhaseUtils"
uuid = "0a972ece-1c72-4cf4-81fb-1c0dc9b4cac1"
authors = ["Oleg Soloviev <oleg.soloviev@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
FFTW = "1"
julia = "1"
