name = "PhaseUtils"
uuid = "0a972ece-1c72-4cf4-81fb-1c0dc9b4cac1"
authors = ["Oleg Soloviev <oleg.soloviev@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
julia = "1"
